### PR TITLE
Rebasing to Alpine 3.10

### PR DESCRIPTION
**Pull request by thelamer**
This is part of a mass upgrade to 3.10. 

Basic smoke test should be performed before merging and notes should be tracked in the internal 3.10 Spreadsheet.

### CODE REVIEW

**Comment by CHBMB** [comment]
@thelamer Hope you don't mind but incorporated some other changes, have tested the 3.10 branch and it seems to be working afaict but there is a pending PR and some readme fixes that close a couple of existing issues so might as well kill 3 birds with one stone.

See here 

https://github.com/linuxserver/docker-domoticz/issues/49 and https://github.com/linuxserver/docker-domoticz/pull/54

We should get @tobbenb to make any readme changes requested as well so we can kill 3 birds with one stone.

See here https://github.com/linuxserver/docker-domoticz/issues/41 and https://github.com/linuxserver/docker-domoticz/pull/54#issuecomment-502494150

**Comment by tobbenb** [comment]
Not much time, but will see if I manage to do it this week.

**Comment by tobbenb** [comment]
Lets kill 4 birds!

**Comment by tobbenb** [comment]
Someone that didn't push to this should probably approve it...

**Pull request merged**
