### PR TITLE
Add python-miio

### PR DESCRIPTION
**Pull request by charger**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

##  Thanks, team linuxserver.io

This is my try to add `python-miio` library which allows controlling Xiaomi vacuum cleaner, wi-fi sockets, IR universal remote and etc.
Can be useful for [domoticz-mirobot-plugin](https://github.com/mrin/domoticz-mirobot-plugin) and for cli commands.

### CODE REVIEW

**Comment by tobbenb** [comment]
Jenkins test this please

**Comment by tobbenb** [comment]
I think this will need to be in it's own container. I have tested this here, but you PR does not make it work.
I'll try to move the server in it's own container and then only the domoticz plugin needs to be added to the plugins folder.

**Comment by charger** [comment]
I'll close this PL

**Comment by bierdok** [comment]
@charger ,
You can install mirobo thanks to the following Ansible task after container creation:

```
- name: Domoticz container - Install mirobo
  shell: |
   docker exec domoticz apk add --no-cache gcc libc-dev libffi-dev linux-headers openssl-dev
   docker exec domoticz pip3 --no-cache-dir install python-miio
  tags: docker

```

**Pull request closed without merging**
