### PR TITLE
ssl keygen

### PR DESCRIPTION
**Pull request by sparklyballs**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]
	

##  Thanks, team linuxserver.io

+ generate a certificate in /config/keys if one doesn't exist, can take some time.... , rather than using shipped default key
+ move root copy to bottom of Dockerfile, allows testing to make use of docker cache and not having to compile every time changing just an init etc.

### CODE REVIEW

**Comment by tobbenb** [comment]
Could you move COPY back to the top so the compiling of domoticz includes support for tellsticks?

**Comment by sparklyballs** [comment]
no, lol.

i'll make two COPY directives though.

**Comment by sparklyballs** [comment]
jenkins retest this please

**Comment by sparklyballs** [comment]
retest this please

**Comment by sparklyballs** [comment]
retest this please

**Pull request merged**
